### ISSUE TITLE
HELP regex pattern

### ISSUE THREAD

**Issue by rjshrjndrn** [wercker/stern#134]
Hi,
thanks for this awesome tool.
I've one small question. Want to find all `http 499` from nginx logs
```
nginx-public-ingress-6x7pb name 106.215.92.25 - - [08/Apr/2020:09:06:15 +0000] "POST /telemetry HTTP/1.1" 499 0 0.039 0.000 ."
```
this is a sample string.
```
stern -i "HTTP\/1.1\" 499"
```
is not working.

Can somebody suggest what should be the pattern?

**Comment by kcy1019** [comment]
It should be `stern -i '"""HTTP\/1.1\"" 499"'`. Because the option is parsed using [golang CSV parser][csv]. :(

[csv]: https://golang.org/pkg/encoding/csv/#pkg-variables

**Comment by rjshrjndrn** [comment]
what I do now is `stern -i 'HTTP.1.1...499'` I think this is the easiest way
