### ISSUE TITLE
how to tail logs from some of the pods

### ISSUE THREAD

**Issue by debu99** [wercker/stern#135]
i just want to get the log from some of the daemon pod, but not all, if there is a way to add a list of pod name or exclude a list for pod name?

**Comment by nvtkaszpir** [comment]
It's already implemented with `-e`, `-i`, `-E` flags

or
`stern something-something | grep --line-buffered` 
;)

**Comment by debu99** [comment]
does -E support a list of pod name, the pod name are random strings, i don't think it is possible to use regex

**Comment by nvtkaszpir** [comment]
https://github.com/wercker/stern/blob/master/stern/tail.go#L48
include/exclude consume regex

**Comment by debu99** [comment]
Sorry, let me use an example to clarify, here below are the list of daemonset of fluentbit, I know that some pods have the log I want, so i want to get the logs only from fluentbit-cs4f5, fluentbit-dxg55, fluentbit-fr894, fluentbit-ltjkn, fluentbit-vcrkx, fluentbit-xmdbb, fluentbit-z84xb, is there easy way to do this?


`NAME              READY   STATUS    RESTARTS   AGE
fluentbit-2hzkh   1/1     Running   0          30h
fluentbit-cs4f5   1/1     Running   0          30h
fluentbit-dxg55   1/1     Running   0          30h
fluentbit-fr894   1/1     Running   0          30h
fluentbit-fzv6z   1/1     Running   0          30h
fluentbit-k92n9   1/1     Running   0          30h
fluentbit-ltjkn   1/1     Running   0          30h
fluentbit-lvlrw   1/1     Running   0          29h
fluentbit-smp96   1/1     Running   0          30h
fluentbit-vcrkx   1/1     Running   0          30h
fluentbit-xmdbb   1/1     Running   0          30h
fluentbit-z84xb   1/1     Running   0          29h`

**Comment by nvtkaszpir** [comment]
try something like `stern 'fluentbit-(cs4f5|dxg55|fr894|ltjkn|vcrkx|vcrkx|xmdbb|z84xb)'`

**Comment by debu99** [comment]
Thanks
