### ISSUE TITLE
Interactive prompt

### ISSUE THREAD

**Issue by droctothorpe** [wercker/stern#153]
I forked and extended stern to include a `--prompt / -p` flag to surface an interactive prompt that looks up values associated with the `app.kubernetes.io/instance` key and lets you select from those options to consume all of the logs associated with a specified Helm chart / ArgoCD application. It's quite useful and could be a good candidate for an upstream contribution. Would you be interested in a PR like that?

Here's an example of usage (disregard the fact that it's called spoke):
![](https://i.imgur.com/ODk4rGb.gif)

**Comment by droctothorpe** [comment]
Following up on this.

**Comment by csantanapr** [comment]
This looks super cool 👍

**Comment by floryut** [comment]
Well as said https://github.com/wercker/stern/issues/148

This repository is no longer maintained, please check https://github.com/stern/stern/issues/120

**Comment by droctothorpe** [comment]
Yep opened an issue there. Thanks! There should be an option to migrate stars.
