### ISSUE TITLE
Exclude name-XXX-YY

### ISSUE THREAD

**Issue by patsevanton** [wercker/stern#157]
Hello! Awasome application!
I try exclude this log

```
js-agent-mongodb-7949d5c4f6-98lzr mongodb {"t":{"$date":"2021-07-16T12:58:39.391+00:00"},"s":"I",  "c":"NETWORK",  "id":22944,   "ctx":"conn102","msg":"Connection ended","attr":{"remote":"127.0.0.1:33104","connectionId":102,"connectionCount":1}}
```

I use
```
stern --exclude 'js-agent-mongodb*' .
```

But log dont hidden. How exclude name-XXX-YY ?
Thanks!

**Comment by floryut** [comment]
@patsevanton As said in https://github.com/wercker/stern/issues/148 and in https://github.com/wercker/stern/issues/155
This project is no longer maintained, please head to https://github.com/stern/stern/ for the up to date one 😄

**Comment by patsevanton** [comment]
Thanks!

**Comment by patsevanton** [comment]
https://github.com/stern/stern/discussions/143
