### ISSUE TITLE
Optionally force colour output

### ISSUE THREAD

**Issue by sublimino** [wercker/stern#33]
Would it be possible to force colour output without a terminal i.e. in a pipe? This would allow `grep`-ing for errors while maintaining stern's useful colourised output.

As a data point, `grep` implements this with a flag:

    $ grep --help | grep color -A 2
      --color[=WHEN],
      --colour[=WHEN]       use markers to highlight the matching strings;
                            WHEN is 'always', 'never', or 'auto'

**Comment by andor44** [comment]
This is a feature that I was looking into myself. Looking at the source `stern` uses [fatih/color](https://github.com/fatih/color) for coloring its output, which in turn uses [go-isatty](https://github.com/fatih/color/blob/master/color.go#L20-L21) to determine if it should color the output or not. Sadly it seems like this is determined simply with the fd and there's no way to override this behavior currently. It might be a good idea to open an issue over on that repo.

**Comment by sublimino** [comment]
@andor44 thanks, issue filed at https://github.com/fatih/color/issues/66

**Comment by sublimino** [comment]
@andor44 thanks, issue filed at https://github.com/fatih/color/issues/66
