### ISSUE TITLE
Add support for filtering log lines

### ISSUE THREAD

**Issue by svenwltr** [wercker/stern#46]
At the moment, `stern` only has a `--exclude` flag, which filters all matching lines. In some cases it would be useful to filter not matching ~~files~~ lines. ie something like an `--include`.

**Comment by reclaro** [comment]
Hi @svenwltr I'd happy to have a look at your request but not sure if I get it correctly. The exclude option exclude some lines of logs, your suggestion instead is something related to the 'not matching files', what does it mean? Which kind of files do you want to include? Thanks

**Comment by svenwltr** [comment]
Hmm ... files was the wrong word here. I meant "lines". 

I would like to do something like this:

```
stern -lapp=solr --include ConnectionLossException
```

So it shows only lines which contain this string.

**Comment by reclaro** [comment]
Hi @svenwltr  thanks for coming back to me so quickly and for the clarification.
Given that stern is a cli tool I think you could  achieve what you want with pipe and grep, following your example:
`stern -lapp=solr | grep  ConnectionLossException`

I am going to close this issue, if you think I am missing something or you have a more complicated use case, please feel free to re-open it.
Thanks

**Comment by akupila** [comment]
FYI: with `grep` you'll lose the colorization by default. You can get around this by using the `--color` flag:
```
stern -lapp=solr --color=always | grep ConnectionLossException
```

**Comment by svenwltr** [comment]
Ok, but skipping `grep` would save some chars on daily work. Especially when I need colored output.

Also then I don't get the purpose of the `--include` flag. You could also use `grep` for this:

```
stern -lapp=solr --color=always | grep -v ConnectionLossException
```
