### ISSUE TITLE
failed to get current user: user: Current not implemented on linux/amd64

### ISSUE THREAD

**Issue by ekuefler** [wercker/stern#5]
I get an error when trying to run stern inside the Debian Docker container where I do most of my development. I assume I'm missing some dependency, but no idea which:

```
# wget https://github.com/wercker/stern/releases/download/1.0.0/stern_linux_amd64
# chmod +x stern_linux_amd64
# ./stern_linux_amd64 mypod
2016/10/31 10:45:12 failed to get current user: user: Current not implemented on linux/amd64
```

**Comment by jnbnyc** [comment]
Hi @ekuefler,

This is a golang cross compilation error.
I was able to use stern in a docker container (FROM golang:1.8-alpine) by:

```bash
go get -u github.com/kardianos/govendor

mkdir -p ${GOPATH}/src/github.com/wercker
cd ${GOPATH}/src/github.com/wercker
git clone --depth 1 https://github.com/wercker/stern.git && cd stern
govendor sync
go install

```

See this for more details: https://stackoverflow.com/questions/20609415/cross-compiling-user-current-not-implemented-on-linux-amd64
