### ISSUE TITLE
Provide homebrew installation

### ISSUE THREAD

**Issue by fiunchinho** [wercker/stern#50]
It'd be cool for mac users to have a homebrew installation.

**Comment by jhinds** [comment]
Looks like one exists already https://github.com/Homebrew/homebrew-core/blob/master/Formula/stern.rb

**Comment by fiunchinho** [comment]
Cool! Thank you

**Comment by kenden** [comment]
PR https://github.com/wercker/stern/pull/57

**Comment by cmosetick** [comment]
I was able to `brew install stern` today, so I think this can be closed.
