### ISSUE TITLE
Handle multiple kubeconfig files

### ISSUE THREAD

**Issue by stuart-warren** [wercker/stern#52]
As per https://github.com/wercker/stern/issues/45#issuecomment-307221903 stern doesn't handle multiple files specified in `KUBECONFIG`.

This is [supported by kubectl](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/)

Currently gives the following error:
```
(cluster-cit/kube-system) : ~ stuart.warren
$ stern kube-scheduler
failed to get client config: stat /Users/stuart.warren/.kube/config:/Users/stuart.warren/Workspace/src/github.com/stuart-warren/overview-docs/kubeconfig:/Users/stuart.warren/.kube/sso-agent-config: no such file or directory
```

**Comment by elblivion** [comment]
Workaround:

```
$ kubectl config view --raw > .kube/stern
$ stern --kubeconfig .kube/stern mypod*
```
