### ISSUE TITLE
unable to authenticate running inside cluster

### ISSUE THREAD

**Issue by cmosetick** [wercker/stern#60]
stern does not fallback to in-cluster authentication mechanisms.

While running `kubectl` in a container inside a cluster, it can retrieve it's cluster configuration where it's running without a .kube/config file. This is inherent to kubectl, it does not need special command line flags.

For example:
https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/client-go/examples/in-cluster-client-configuration

> _client-go uses the Service Account token mounted inside the Pod at the /var/run/secrets/kubernetes.io/serviceaccount path when the rest.InClusterConfig() is used._

I'm trying to use the Gitlab Kubernetes Deploy image, which has kubectl baked into the image.
Dockerfile: https://gitlab.com/gitlab-examples/kubernetes-deploy/blob/master/Dockerfile
location: `docker pull registry.gitlab.com/gitlab-examples/kubernetes-deploy`

Using that image which has kubectl baked in, you can see that kubectl has no trouble communicating with the cluster. It is able to create a namespace and pod. (kubectl is running in a container on the cluster)

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"8+", GitVersion:"v1.8.0-alpha.2", GitCommit:"8e5584fe95c01f2b3a9d60fcccef8fadbb4c8f88", GitTreeState:"clean", BuildDate:"2017-07-12T21:29:15Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.2", GitCommit:"922a86cfcd65915a9b2f69f3f193b8907d741d9c", GitTreeState:"clean", BuildDate:"2017-07-21T08:08:00Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl cluster-info
Kubernetes master is running at https://100.64.0.1:443
KubeDNS is running at https://100.64.0.1:443/api/v1/namespaces/kube-system/services/kube-dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
$ kubectl apply -f k8s/
namespace "my-namespace" configured
pod "my-pod" created
```
However at the same moment, stern is not able to authenticate to the cluster:
```
./stern -n my-namespace -l name=my-app
failed to get client config: stat /root/.kube/config: no such file or directory
```
Stern is very useful because it can be launched and wait for items that are not even running on the cluster yet.
While the use cases for such a feature may be limited, it could still be incredibly useful to authenticate to the cluster using the native mechanisms already present in Kubernetes itself.

**Comment by dineshba** [comment]
Is this useful feature? If so, I would like to contribute to it. Please lemme me know if this is useful

**Comment by everpeace** [comment]
FYI: stern/stern#9 fixed this issue.

**Comment by cmosetick** [comment]
PR https://github.com/stern/stern/pull/93 by @everpeace seems to fix this issue. Closing for now. Thanks again @everpeace!!
