### ISSUE TITLE
support --include in addition to --exclude

### ISSUE THREAD

**Issue by majewsky** [wercker/stern#66]
Since there's `--exclude`, I found it quite surprising to not see its mirror, `--include`. The obvious example usecase is

    stern '.*' --include ERROR

to see all errors that occur anywhere.

**Comment by stevenklar** [comment]
Made a pull request which does the same like exclude but the other way arround... simple but it works :100:

**Comment by indrayam** [comment]
@stevenklar Let us know if and when it gets merged into the master. Btw, can you share a screenshot of what the behavior looks like. Not if it is going to take too much of your time though. Just was super interested!

**Comment by stevenklar** [comment]
Here is the terminal output... which would look the same on a screen. ;-)

> ➜  stern cool-tool
```
+ some-cool-tool-c4dfc7f68-4fhzk › cool-tool
some-cool-tool-c4dfc7f68-4fhzk cool-tool AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 1.3.3.7. Set the 'ServerName' directive globally to suppress this message
some-cool-tool-c4dfc7f68-4fhzk cool-tool AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 1.3.3.7. Set the 'ServerName' directive globally to suppress this message
some-cool-tool-c4dfc7f68-4fhzk cool-tool [Thu Jan 24 20:50:49.842994 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.2.3 configured -- resuming normal operations
some-cool-tool-c4dfc7f68-4fhzk cool-tool [Thu Jan 24 20:50:49.843086 2019] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```


> ➜  stern cool-tool --include "PHP"
```
+ some-cool-tool-c4dfc7f68-4fhzk › cool-tool
some-cool-tool-c4dfc7f68-4fhzk cool-tool [Thu Jan 24 20:50:49.842994 2019] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.25 (Debian) PHP/7.2.3 configured -- resuming normal operations
```

**Comment by indrayam** [comment]
Awesome. Good stuff!

**Comment by stevenklar** [comment]
I just published a preview release with the binary attached.

Keep in mind before downloading the binary that building it yourself to know what's inside the binary is always the best idea.

https://github.com/stevenklar/stern/releases/tag/1.11.0-preview

**Comment by stevenklar** [comment]
@indrayam not yet. We need to wait for the maintainer to test the new feature and release a new version when they feel it's allright.

**Comment by NaffanDroo** [comment]
plus one for this to make it through :)

**Comment by stevenklar** [comment]
Well. I allow any person who signed the OCA to copy my stuff and sign it with his own name, so this feature does get merged.

**Comment by stevenklar** [comment]
OCA has been signed. Just waiting for approval.

**Comment by stevenklar** [comment]
Officialy on the page now. :ocean:

**Comment by indrayam** [comment]
@stevenklar Which page? Can you provide a link?

**Comment by stevenklar** [comment]
Just mean the OCA page which allows to merge my PR.
